services:
  web:
    image: your_dockerhub_username/otus_final_project:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/tasks?sslmode=disable

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
