name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v3  # Обновлено на v3

      - name: Установка Go
        uses: actions/setup-go@v3  # Обновлено на v3
        with:
          go-version: '1.22.2'  # Укажите вашу версию Go

      - name: Установка golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Линтинг
        run: golangci-lint run ./...

      - name: Запуск тестов
        run: go test -race -count=100 ./...

      - name: Сборка
        run: go build -o myapp .
