name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.2'  # Замените на нужную вам версию Go

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Run tests
        run: go test -race -count=100 ./...
